### ISSUE TITLE
not only organisation repos

### ISSUE THREAD

**Issue by IpekUyguner** [src-d/gitcollector#92]
Hi,
Can we also obtain users' repos,  not only organization by plain command?

**Comment by smola** [comment]
@IpekUyguner source{d} is out of business (https://github.com/src-d/datasets/issues/171#issuecomment-571944947) and all its projects discontinued. Some projects are maintained elsewhere (https://github.com/src-d/guide/issues/385). Part of the former team now works at [Athenian](https://www.athenian.co/), where you can find a commercial offering.
